### ISSUE TITLE
Feature request: get a list of vaults

### ISSUE THREAD

**Issue by chrisky** [MoriTanosuke/glacieruploader#44]
Like the tool - it's straightforward to use.  
Would it be feasible to include some mechanism whereby you could get a list of the available vaults?

**Comment by MoriTanosuke** [comment]
The API definitely allows listing all vaults: https://docs.aws.amazon.com/amazonglacier/latest/dev/api-vaults-get.html

I'll check the Java SDK and will try to build that feature. :+1:

**Comment by MoriTanosuke** [comment]
@chrisky You can give it a try, download release from https://github.com/MoriTanosuke/glacieruploader/releases/tag/0.0.8
