### ISSUE TITLE
Received Job ID with leading dash ('-')

### ISSUE THREAD

**Issue by thyberg** [MoriTanosuke/glacieruploader#49]
Hi,
I am trying out glacieruploader and was trying to issue an inventor listing command and the
job ID I received started with a hyphen...

~/bin/glacier-cmd.sh -l
2016-feb-07 10:00:47 de.kopis.glacier.GlacierUploader findAndExecCommand
INFO: Using end point: https://glacier.eu-west-1.amazonaws.com
2016-feb-07 10:00:48 de.kopis.glacier.commands.RequestArchivesListCommand startInventoryListing
INFO: Starting inventory listing for vault backup...
2016-feb-07 10:00:50 de.kopis.glacier.commands.RequestArchivesListCommand startInventoryListing
INFO: Inventory Job created with ID
-zoDBAz5dT5tyfv9Rf-pvGbijIqDs_gpL30ud2zq1-qa4Azz11a-ABCGIS4bzbUmCzeg2U3xMrp9W6PWHV9UTaKSTX-g

Later when trying to use that job ID with the "-l" option I got
 ~/bin/glacier-cmd.sh -l -zoDBAz5dT5tyfv9Rf-pvGbijIqDs_gpL30ud2zq1-qa4Azz11a-ABCGIS4bzbUmCzeg2U3\
xMrp9W6PWHV9UTaKSTX-g
Something went wrong parsing the arguments

It looks like that the ID is parsed as an option and that fails.
Is there some way to quote an ID to prevent the command line parsing library
from treating the ID as an command option?

**Comment by MoriTanosuke** [comment]
Did you try to put the parameter in "?

    ~/bin/glacier-cmd.sh -l "-zoDBAz5dT5tyfv9Rf-pvGbijIqDs_gpL30ud2zq1-qa4Azz11a-ABCGIS4bzbUmCzeg2U3xMrp9W6PWHV9UTaKSTX-g"

**Comment by thyberg** [comment]
~/bin/glacier-cmd.sh -l "-zoDBAz5dT5tyfv9Rf-pvGbijIqDs_gpL30ud2zq1-qa4Azz11a-ABCGIS4bzbUmCzeg2U3xMrp9W6PWHV9UTaKSTX-g"
Something went wrong parsing the arguments

And the reason for that not working is that it is not the shell that prints the error message "Something went wrong parsing the arguments", but the command line parsing library. 
There ought to be a way to instruct that library to *not* to any option parsing on the arguments itself.

**Comment by thyberg** [comment]
After having look at the jopt-simple project I noticed that one can write the arguments like this.
~/bin/glacier-cmd.sh -l=-zoDBAz5dT5tyfv9Rf-pvGbijIqDs_gpL30ud2zq1-qa4Azz11a-ABCGIS4bzbUmCzeg2U3xMrp9W6PWHV9UTaKSTX-g
that is, with an equal sign format. '.l=foo'.
Case closed (at least for me)

**Comment by MoriTanosuke** [comment]
Good to hear you found a way to solve this. I'll add it to the README.
