### ISSUE TITLE
HumanReadableSize cannot handle file sizes larger than 10GB

### ISSUE THREAD

**Issue by thyberg** [MoriTanosuke/glacieruploader#50]
I have found a problem with the `HumanReadableSize` class in that it does not
handle large files properly. It seems to happen with files > 10GB in size.
I have two examples (cut from a glacier -l command).
```
74397132 (70.96MB)
9807947179 (9.14GB)
19008123152 (7.00kB)
73476694570 (7.00kB)
```
When you call `parse("73476694570")` you will end up with a `sizeAsDouble / 1024`
as the value `7.175458454101562E7`. Looking further into the `sanitize()` method
it seems that it cannot handle doubles in exponential format, e.g. `8.1234E8`.

Of the following tests the first two fails on my machine.
(Put them in HumanReadableSizeTest.java)
```
@Test
public void terabyteLargeSizeFailed() {
    assertEquals("68TB", HumanReadableSize.parse("75240135239680"));
}

@Test
public void gigabyteLargeSizeFailed() {
    assertEquals("68GB", HumanReadableSize.parse("73476694570"));
}

@Test
public void megabyteLargeSizeFailed() {
    assertEquals("68.44MB", HumanReadableSize.parse("71754584"));
}
```

**Comment by MoriTanosuke** [comment]
Nice catch. Thanks for reporting. :+1: 

I created branch [fix-50](https://github.com/MoriTanosuke/glacieruploader/tree/fix-50) where I replaced the `double` with actual `BigDecimal`. Can you give it a try?

I guess I wasn't thinking about archives that large. :eyes:

**Comment by thyberg** [comment]
I have now had the time to try out the fix-50 branch and it do handle large files OK now.
