### ISSUE TITLE
Make it a library?

### ISSUE THREAD

**Issue by arichiardi** [MoriTanosuke/glacieruploader#51]
It would be awesome to have the `Command` part (very nice indeed) as part of a maven package so that it can be used in client code with ease.

Good job by the way!

**Comment by MoriTanosuke** [comment]
Interesting, I never thought about that part becoming a library. How would you want to use it? Can you give me a few examples of your workflow?

**Comment by arichiardi** [comment]
An example would be to use it in another part that does the diffing, or embed it in a UI. In my particular case I was thinking of embedding it in some Clojure app.

**Comment by MoriTanosuke** [comment]
I just pushed the branch [split-into-modules][0]. Just a quick try to move everything into submodules, the dependencies are still messy - but it builds and the tests still run. Can you give it a look and see if this would help you with your goal?

[0]: https://github.com/MoriTanosuke/glacieruploader/tree/split-into-modules

**Comment by arichiardi** [comment]
My 2c: maybe it is a bigger split than I imagined. The Commands are great, I see that I have everything in there that can be included in client code. I don't know what the parser role is and I would need it somehow as utility function in order to parse an external configuration, maybe yes.
Sorry I have not investigated what the code does enough to say what can be useful in a library and what not.

Maybe just separating the "utilities" from the "command line" related stuff is enough, and then upload the two packages (or the utilities only) as maven dependency.

Thanks for helping on this!

**Comment by MoriTanosuke** [comment]
Ah yes, basically the `glacieruploader-printers` and `glacieruploader-parsers` are handling the command line part. There's some nasty coupling going on which I didn't resolve yet. I'll have another look at it tomorrow and clean it up a bit. This will clean the code up anyway, and maybe it is useful for someone else too.

I'm not sure how to upload something to the *central* repository though. I know there's a way to provide a repository via GitHub, I'll look into this too.

**Comment by arichiardi** [comment]
Yeah the procedure is not as easy as it should be, you have to register to Sonatype etc, etc...., some links below (the first for gradle but it is the same if you use `mvn`).

http://www.sonatype.org/nexus/2015/04/28/how-to-publish-your-open-source-library-to-maven-central/
http://central.sonatype.org/pages/apache-maven.html
https://maven.apache.org/plugins/maven-deploy-plugin/

**Comment by MoriTanosuke** [comment]
Thanks for the links. 👍☺

**Comment by MoriTanosuke** [comment]
Here are some more links to documentation about getting software into *central*

* https://maven.apache.org/guides/mini/guide-central-repository-upload.html
* https://www.apache.org/dev/publishing-maven-artifacts.html
* http://central.sonatype.org/pages/choosing-your-coordinates.html

Probably a good *groupId* would be *com.github.moritanosuke*, although I do like *de.kopis* for my stuff.

**Comment by MoriTanosuke** [comment]
I am currently cleaning up the POM and adding a couple of plugins with the recommended configuration to deploy to Sonatypes repository later. In the meantime I opened a new issue to create a *groupId* for the project: https://issues.sonatype.org/browse/OSSRH-24609

**Comment by MoriTanosuke** [comment]
I merged the branch with the seperated submodules into *master*. I also did my first release into *central*. I'll update and close this issue when the artifacts are available. :smile:

**Comment by MoriTanosuke** [comment]
Ok, it's now available at https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22de.kopis.glacier%22

Hope this is useful to some.

**Comment by arichiardi** [comment]
Thanks @MoriTanosuke it looks like it will be useful to some :dancer: I will probably need to ask you some question about the implementation if I cannot figure it out (I am looking at the `TreeHashArchiveCommand` for instance) but for now thanks for your work!
