### ISSUE TITLE
Status update enhancement?

### ISSUE THREAD

**Issue by davedwca** [MoriTanosuke/glacieruploader#56]
It would be nice to have a status of the upload progress at the command line.  Is this doable - I would be willing to contribute.  I was thinking that every 30 seconds it prints a % complete.  Sorry - I know this is more of a think-tank than an issue

**Comment by MoriTanosuke** [comment]
No problem, the issues can also be used for discussion and ideas.

I implemented a very basic version of the progress update using Amazons `ProgressTracker`. The upload now prints the transferred and total bytes. I build a version with this change, you can download it from https://github.com/MoriTanosuke/glacieruploader/releases/tag/0.1.1-beta1

Give it a try and tell me if this is how you imagined it. Currently it's very rough, printing the progress each second. I think it would be nice to make this configurable via the config, so the interval can be modified.

**Comment by MoriTanosuke** [comment]
Progress is currently printed like this:

````
#java -jar glacieruploader.jar --region MYREGION --vault MYSUPERVAULT --upload MYSUPERFILE 
INFO  Using region: MYREGION 
INFO  Starting to upload MYSUPERFILE to vault MYSUPERVAULT...
INFO  240510/64105342 transferred
INFO  543614/64105342 transferred
INFO  846718/64105342 transferred
INFO  1141630/64105342 transferred
INFO  1436542/64105342 transferred
INFO  1731454/64105342 transferred
INFO  2034558/64105342 transferred
...
````

**Comment by davedwca** [comment]
Yes, that is exactly what I had in mind.  It would be better if you could add a percent to it since the numbers are hard to see when they scroll: INFO  1436542/64105342 transferred **(2%)**. 

Your documentation makes the utility easy to use.  For the beta, I found a couple of things: a) The reporting loop doesn't end after the file uploads.  b)Region required when using the --help option. c) Exception stack dump when listing the contents of an empty vault.
