### ISSUE TITLE
The --list-inventory command now demands an argument

### ISSUE THREAD

**Issue by thyberg** [MoriTanosuke/glacieruploader#57]
Just tried out the 0.1.1-beta1 version but that one does not allow a simple "-l".
Previously one called it without an argument to get a job-ID to be used to retried the inventory listing.

It seems that RequestArchivesListCommand#valid has got an added 
   options.has(optionParser.vault) 

Adding a "-vault=backup" on the commandline and it works.

I do have vault=backup in my ~/.glacieruploaderrc but that seems to be ignored for
the "-l" option.

I removed "options.has(optionParser.vault) &&" in the valid()-method and
things worked again.

Is this a bug or have things changed how you now perform a "-l"?

**Comment by MoriTanosuke** [comment]
Hm, looks like I added the vault option to the command in commit 66a9e96130a5c2640022300b0ad21b24845deabe. The documentation also shows both the list inventory and the display result job with a vault name, so I guess it was just an oversight on my part.

I'll check the argument handling later. Maybe I also broke the overriding via `~/.glacieruploaderrc` with that change too.

**Comment by MoriTanosuke** [comment]
I removed the mandatory argument from the command and also fixed the override from system environment/configuration file. It's available on branch *bugfix/57*.

@thyberg Can you give it a try? If it works for you I'll merge it into master and create a new beta release for others.

**Comment by thyberg** [comment]
"-l" now works and a hash is returned but when I try to use the returned hash, i.e.
-l YCWZEWsy15xs ...... WQZ3jdB_sjflvDajmL0qUjN2QjMOIeWyyPeuhhvDMtn

I get the following 
`ERROR Unable to marshall request to JSON: Unable to marshall request to JSON: Parameter 'vaultName' must not be null
com.amazonaws.SdkClientException: Unable to marshall request to JSON: Unable to marshall request to JSON: Parameter 'vaultName' must not be null
	at com.amazonaws.services.glacier.model.transform.GetJobOutputRequestProtocolMarshaller.marshall(GetJobOutputRequestProtocolMarshaller.java:58)
	at com.amazonaws.services.glacier.AmazonGlacierClient.executeGetJobOutput(AmazonGlacierClient.java:1394)`

It seems that the vault is not recognized. I have tried both having "vault=backup" in my
~/.glacieruploaderrc
and using "-v" but no success.

**Comment by MoriTanosuke** [comment]
Ah, sorry for that. I pushed another commit to fix this. Tested right now with a `.glacieruploaderrc` on my machine.

**Comment by thyberg** [comment]
Now it works! Well I assume it works since there is no result to download yet :-)

`com.amazonaws.services.glacier.model.InvalidParameterValueException: The job is not currently available for download: YCWZ .... uhhvDMtn (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: v_RcyXiP-kheTDinS10SaMywJnc3X8LNwXcWYZezhhOOHjo)`

**Comment by MoriTanosuke** [comment]
Yes, as long as the Amazon SDK doesn't complain about missing parameters... 😎 I'm going to merge this later and will upload a new release.

**Comment by MoriTanosuke** [comment]
Merged into *master*.
