### ISSUE TITLE
0.1.1-beta1 Inventory command/option (-l) now gives erroneous sizes

### ISSUE THREAD

**Issue by thyberg** [MoriTanosuke/glacieruploader#58]
Precious version 
CreationDate:			2016-02-14T20:34:00Z
Size:				73476694570 (68.44GB)

0.1.1.-beta1
CreationDate:			2016-02-14T20:34:00Z
Size:				462250538 (440.84MB)

Converting the sizes to hex reveals a problem with the hi-order bytes.
For example, the sizes from above:
printf "%x\n" 73476694570
111b8d622a

printf "%x\n" 462250538
1b8d622a

Some more examples:
printf "%x\n" -1043299672
ffffffffc1d082a8
printf "%x\n" 24726504104
5c1d082a8

printf "%x\n" -745626463
ffffffffd38ea4a1
printf "%x\n" 12139275425
2d38ea4a1

printf "%x\n" 2096187049
7cf146a9
printf "%x\n" 70815663785
107cf146a9

**Comment by MoriTanosuke** [comment]
Hm, I can not yet reproduce the issue on my side, but I don't have really large archives in my vault.

The only thing I can imagine going wrong is getting the size as an `Integer` at https://github.com/MoriTanosuke/glacieruploader/blob/862f11cd1ed959da881bb809e6095a362ea6da43/glacieruploader-printers/src/main/java/de/kopis/glacier/printers/VaultInventoryPrinter.java#L74 I added branch *bugfix/58* and changed the `Integer` to a `BigDecimal`.

@thyberg Can you maybe add a test to https://github.com/MoriTanosuke/glacieruploader/blob/bugfix/58/glacieruploader-printers/src/test/java/de/kopis/glacier/printers/VaultInventoryPrinterTest.java ?

**Comment by thyberg** [comment]
Just paste the following into the test file using the data from above " Size: 73476694570 (68.44GB)"
```
    @Test
    public void test68GbLargeInventorySizeInteger() {
        final JSONObject inventoryJson = new JSONObject("{\"Size\": 73476694570 }");
        final String readableSize = VaultInventoryPrinter.printArchiveSize(inventoryJson);
        assertEquals("73476694570 (68.44GB)", readableSize);
    }
```

Also, make this method `VaultInventoryPrinter.printArchiveSize`static since it does not have any dependencies to the class. That way there is no need to make an instance of that class just to call this method.

If tested it locally and it seems that the BigInteger solves this.
I see that in the version where it works the `size`field was extracted as a string and then converted.
Well, now there is (at least) one unit test catching that :-)

**Comment by MoriTanosuke** [comment]
@thyberg Thanks for your input and the testcase. :+1:
