### ISSUE TITLE
Upload does not return/complete

### ISSUE THREAD

**Issue by sktouchst** [MoriTanosuke/glacieruploader#60]
The command does not return after the upload completes.

INFO  Uploaded archive XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred
INFO  30111589/30111589 transferred

It just goes on until I Control-C.

**Comment by sktouchst** [comment]
I am using version glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar.

**Comment by MoriTanosuke** [comment]
@sktouchst Please check https://github.com/MoriTanosuke/glacieruploader/releases/tag/0.1.1-beta2 

I want to add and improve the progress printer for all upload/download commands, but I don't know when I'll get around to do it.
