### ISSUE TITLE
Command "list-jobs" asks for an unnecessary argument

### ISSUE THREAD

**Issue by devtobo** [MoriTanosuke/glacieruploader#61]
Hi,
I am trying to list the files in my vault (for downloading them later). I am using the snapshot:
glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar

`java -jar glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --endpoint https://glacier.us-east-1.amazonaws.com --vault MyVault -l`

```
INFO  Using region: us-east-1
INFO  Starting inventory listing for vault MyVault...
INFO  Inventory Job created with ID 2tIae4jFiovOH4XZ3Q-umtJm-l6E4uL-2oxkSJVEYEM3UJAodH4MArWP20NvDVLp5ncIpXBXtdYEXFwoG8_Kb-QFo_bG
```

*Trying to use the Job ID...*

`java -jar glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --endpoint https://glacier.us-east-1.amazonaws.com --vault MyVault --list-inventory 2tIae4jFiovOH4XZ3Q-umtJm-l6E4uL-2oxkSJVEYEM3UJAodH4MArWP20NvDVLp5ncIpXBXtdYEXFwoG8_Kb-QFo_bG`

```
INFO  Using region: us-east-1
INFO  Retrieving inventory for job id 2tIae4jFiovOH4XZ3Q-umtJm-l6E4uL-2oxkSJVEYEM3UJAodH4MArWP20NvDVLp5ncIpXBXtdYEXFwoG8_Kb-QFo_bG...
ERROR The job is not currently available for download: 2tIae4jFiovOH4XZ3Q-umtJm-l6E4uL-2oxkSJVEYEM3UJAodH4MArWP20NvDVLp5ncIpXBXtdYEXFwoG8_Kb-QFo_bG (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: NYBKpfrWDYRfOH1LzcQKkGmJf00Yj6ANo5LfwW1lQ2_q1Yc)
com.amazonaws.services.glacier.model.InvalidParameterValueException: The job is not currently available for download: 2tIae4jFiovOH4XZ3Q-umtJm-l6E4uL-2oxkSJVEYEM3UJAodH4MArWP20NvDVLp5ncIpXBXtdYEXFwoG8_Kb-QFo_bG (Service: AmazonGlacier; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: NYBKpfrWDYRfOH1LzcQKkGmJf00Yj6ANo5LfwW1lQ2_q1Yc)
```

*Also cannot list jobs:*

`java -jar glacieruploader-impl-0.1.1-SNAPSHOT-jar-with-dependencies.jar --endpoint https://glacier.us-east-1.amazonaws.com --vault MyVault --list-jobs`

```
ERROR Something went wrong parsing the arguments
joptsimple.OptionMissingRequiredArgumentException: Option ['j', 'list-jobs'] requires an argument
```

**Comment by MoriTanosuke** [comment]
The first message `The job is not currently available for download` indicates that the inventory listing is not yet ready. I'd try again later, sometimes it takes quite a long time to actually complete.  There is a way to configure notifications for vault operations though: https://docs.aws.amazon.com/amazonglacier/latest/dev/configuring-notifications-console.html

The second message `Option ['j', 'list-jobs'] requires an argument` indicates that an argument is missing. The code checks for an argument, but I think that is an mistake: 

https://github.com/MoriTanosuke/glacieruploader/blob/c5aed2f6dd5f9df55b8fe6668eb3ce0ab63e9473/glacieruploader-command/src/main/java/de/kopis/glacier/commands/ListJobsCommand.java#L75-L77

I'll check that one.

**Comment by MoriTanosuke** [comment]
@devtobo Good to hear. I'll rename this issue to track the unnecessary argument for the `list-jobs` command then.
