### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by maferra** [MoriTanosuke/glacieruploader#63]
Dear MoriTanosuke,

Perhaps I have found an error with glacieruploader, or maybe something has changed; last Friday (16-02-2017) I have successfully made a multi-part upload of a 10 GB file to glacier, but today (19-02-2017) I'm unable to issue a simple list-jobs command. I have tried to debug the connection, but I'm having trouble on understanding were could be the issue. I have attached the logged file [glacieruploader.log](https://github.com/MoriTanosuke/glacieruploader/files/1736168/glacieruploader.log). Can you see the error?

Thank you for glacieruploader and best regards.

**Comment by MoriTanosuke** [comment]
Hm, the logfile looks like there is a connection error to the AWS cloud. Could be a connectivity issue on your side (the logfile does not show a proxy configured) or on AWS side.

**Comment by maferra** [comment]
Yes! You are correct:

The problem was that I was running:

`$ java -Dhttp.proxyHost=server -Dhttp.proxyPort=3128 -jar glacieruploader-impl-0.1.1-jar-with-dependencies.jar --list-jobs`

But should be doing:

`$ java -Dhttps.proxyHost=server -Dhttps.proxyPort=3128 -jar glacieruploader-impl-0.1.1-jar-with-dependencies.jar --list-jobs`

Because on the AWS side there is a secure (https) server, so it should be **https.proxyHost** and **https.proxyPort**, so no problem with glacieruploader whatsoever.

Thank you once again for directing me in the right direction.

**Comment by MoriTanosuke** [comment]
Glad I could help. 😄

**Comment by maferra** [comment]
Excellent! Thank you. Perhaps just two tips. For Windows users: to make it easier to configure the proxy's server and port, it can be added to the environment this variable:

`JAVA_TOOL_OPTIONS=-Dhttps.proxyHost=server -Dhttps.proxyPort=3128`

Instead of passing always directly through the command line. This environment variable will be picked up by the java command line tool.

Another tip is that when starting a multi-part upload, if issuing:

`java -jar glacieruploader-impl-0.1.1-jar-with-dependencies.jar -m filename`

glacieruploader will immediately exit because there wasn't passed the -p argument. But if -p already has a default value and we are making a multi-part upload, perhaps glacieruploader could assume that we want an upload with a default chuck size, becaming -p optional.

I suppose it's a detail. Thank you very much for glacieruploader.
