### ISSUE TITLE
I have problem with credentials

### ISSUE THREAD

**Issue by julianalmanzar** [MoriTanosuke/glacieruploader#65]
Hello,
I'm having a bad time usong my credentials. I tried creating a file named "mysecretaws.properties" with them inside. but it seems not to work. How can i specify where are my credentials correctly? I'm using the binary btw. Thanks in advance.

**Comment by MoriTanosuke** [comment]
Here is the official AWS documentation https://docs.aws.amazon.com/cli/latest/userguide/cli-config-files.html

glacieruploader supports the same configuration. The [README][0] has a section on credentials too.

[0]: https://github.com/MoriTanosuke/glacieruploader/blob/master/README.md#how-to-run
