### ISSUE TITLE
Unable to access jarfile

### ISSUE THREAD

**Issue by jimmiejackson414** [MoriTanosuke/glacieruploader#68]
I'm going to go ahead and apologize for such an incredible newbie question, but here goes...

I'm simply trying to view a list of my archives and its contents. I am brand new to the Java world (typically only work in Ruby/React web dev). After downloading Java and cloning the repo, then cd-ing into that new directory, I attempt to run the application with `java -jar glacieruploader.jar` by itself, or with an endpoint and vault name. Any command I try returns the message `Error: Unable to access jarfile glacieruploader.jar`.

What obvious mistake am I doing?

Thank you very much!

**Comment by MoriTanosuke** [comment]
@jimmiejackson414 no problem, everyone starts somewhere.

The error message usually comes up when the path to the JAR is wrong. Can you paste the output of `ls -l` in the directory where you want to start the application?

**Comment by jimmiejackson414** [comment]
`total 160
-rw-r--r--  1 jimmiejackson  staff    35K Aug  8 21:40 LICENSE.txt
-rw-r--r--  1 jimmiejackson  staff    10K Aug  8 21:40 README.md
-rw-r--r--  1 jimmiejackson  staff     0B Aug  8 21:40 RELEASE.md
drwxr-xr-x  5 jimmiejackson  staff   160B Aug  8 21:40 docs/
drwxr-xr-x  5 jimmiejackson  staff   160B Aug  8 21:41 glacieruploader-command/
drwxr-xr-x  5 jimmiejackson  staff   160B Aug  8 21:41 glacieruploader-impl/
drwxr-xr-x  5 jimmiejackson  staff   160B Aug  8 21:41 glacieruploader-parsers/
drwxr-xr-x  5 jimmiejackson  staff   160B Aug  8 21:41 glacieruploader-printers/
-rwxr-xr-x  1 jimmiejackson  staff   7.1K Aug  8 21:40 mvnw*
-rw-r--r--  1 jimmiejackson  staff   5.0K Aug  8 21:40 mvnw.cmd
-rw-r--r--  1 jimmiejackson  staff    14K Aug  8 21:40 pom.xml
drwxr-xr-x  3 jimmiejackson  staff    96B Aug  8 21:41 target/`

I noticed that glacieruploader.jar isn't present within that directory.

**Comment by MoriTanosuke** [comment]
@jimmiejackson414 Looks like you downloaded the sourcecode instead of the release. You can download the JAR from https://github.com/MoriTanosuke/glacieruploader/releases/tag/glacieruploader-0.1.1.

**Comment by jimmiejackson414** [comment]
Ah, I'm glad it was something simple. Thank you very much!
