### ISSUE TITLE
README.md Instructions to Use Unclear

### ISSUE THREAD

**Issue by patrickscottbest** [MoriTanosuke/glacieruploader#73]
Hi, I followed the instructions (git clone /maven package), but my build did not come out with a "glacieruploader.jar" file.  Instead, I found that this worked for me: 
```

java -jar ./glacieruploader-impl/target/glacieruploader-impl-0.1.2-SNAPSHOT-jar-with-
dependencies.jar --optionsetc

```
Centos7, java 11.0.3.7, Apache Maven 3.0.5

**Comment by MoriTanosuke** [comment]
Uh yes, I didn't specify the path to the JAR file. The instructions are just an example and I don't want to put a full path to the file in there. Updated the README.md to make that more clear and also reference the `glacieruploader-impl` module. Thanks.

**Comment by patrickscottbest** [comment]
cool, thanks!
